language: csharp
solution: Solution1.sln
script:
  - msbuild /p:Configuration=Release Solution1.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./UnitTestProject1/bin/Release/UnitTestProject1.dll
